name: Build Test - Ubuntu-20.04

on:
  push:
    branches:
      - 'OVIS-4'
      - main
      - 'b[0-9]+.[0-9]+'
  pull_request:
    branches:
      - 'OVIS-4'
      - main
      - 'b[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: ovishpc/ovis-ubuntu-build
    steps:
    - uses: actions/checkout@v3
    - run: sh autogen.sh
    - run: ./configure CFLAGS="-Wall -Werror"
    - run: make

  distcheck:
    runs-on: ubuntu-20.04
    container:
        image: ovishpc/ovis-ubuntu-build
    steps:
    - uses: actions/checkout@v3
    - run: sh autogen.sh
    - run: ./configure
    - run: make distcheck

  build-with-rdma:
    runs-on: ubuntu-20.04
    container:
        image: ovishpc/ovis-ubuntu-build
    steps:
    - uses: actions/checkout@v3
    - run: sh autogen.sh
    - run: ./configure --enable-rdma CFLAGS="-Wall -Werror"
    - run: make
