name: Test "make dist"

on:
  push:
    branches:
      - 'OVIS-4'
      - main
      - 'b[0-9]+.[0-9]+'
  pull_request:
    branches:
      - 'OVIS-4'
      - main
      - 'b[0-9]+.[0-9]+'

jobs:
  build:
    # Make sure that create-release.yaml has the same "runs-on" and
    # "container" as used here.
    runs-on: ubuntu-20.04
    container:
        image: ovishpc/ovis-ubuntu-build

    steps:
    - uses: actions/checkout@v3
    - name: autogen
      run: sh autogen.sh
    - name: configure
      run: ./configure
    - name: make dist
      run: make dist
